# Generated by Django 5.0.3 on 2024-04-04 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('related', '0002_alter_related_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='related',
            old_name='related_title',
            new_name='title',
        ),
    ]
